-- ERD Studio 서비스 자체 DB 스키마 (PostgreSQL)
-- 실행 중인 앱의 DB에서 pg_dump --schema-only 로 추출 (Hibernate ddl-auto 생성 스키마)
-- 테이블: erd_room(방) / erd_domain(도메인) / erd_table / erd_column / erd_relation / erd_memo(캔버스 메모) / erd_history(스냅샷 이력)

CREATE TABLE public.erd_column (
    id bigint NOT NULL,
    col_type character varying(255) NOT NULL,
    comment character varying(255) NOT NULL,
    flag character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    sort_order integer NOT NULL,
    table_id bigint NOT NULL
);
ALTER TABLE public.erd_column ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_column_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_domain (
    id bigint NOT NULL,
    color character varying(255) NOT NULL,
    key character varying(255),
    name character varying(255) NOT NULL,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL
);
ALTER TABLE public.erd_domain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_domain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_history (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    op jsonb NOT NULL,
    op_kind character varying(255) NOT NULL,
    room_id bigint NOT NULL,
    snapshot jsonb NOT NULL,
    target character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL
);
ALTER TABLE public.erd_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_relation (
    id bigint NOT NULL,
    cardinality character varying(255),
    child_table_id bigint NOT NULL,
    label character varying(255) NOT NULL,
    parent_table_id bigint NOT NULL,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL
);
ALTER TABLE public.erd_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_memo (
    id bigint NOT NULL,
    color character varying(32) NOT NULL,
    memo_key character varying(64) NOT NULL,
    pos_x double precision NOT NULL,
    pos_y double precision NOT NULL,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL,
    text character varying(1000) NOT NULL
);
ALTER TABLE public.erd_memo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_memo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_room (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);
ALTER TABLE public.erd_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.erd_table (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    domain_key character varying(255) NOT NULL,
    is_hub boolean NOT NULL,
    name character varying(255) NOT NULL,
    pos_x double precision,
    pos_y double precision,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL
);
ALTER TABLE public.erd_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.erd_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.erd_column
    ADD CONSTRAINT erd_column_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_domain
    ADD CONSTRAINT erd_domain_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_history
    ADD CONSTRAINT erd_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_relation
    ADD CONSTRAINT erd_relation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_memo
    ADD CONSTRAINT erd_memo_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_memo
    ADD CONSTRAINT uk_erd_memo_room_key UNIQUE (room_id, memo_key);
ALTER TABLE ONLY public.erd_room
    ADD CONSTRAINT erd_room_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_table
    ADD CONSTRAINT erd_table_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.erd_table
    ADD CONSTRAINT uk4hlkbjdigdwlio21r1g9kasj6 UNIQUE (room_id, name);
ALTER TABLE ONLY public.erd_domain
    ADD CONSTRAINT uk7we1hrnjsooa8hqyabwkvtrwn UNIQUE (room_id, key);
ALTER TABLE ONLY public.erd_room
    ADD CONSTRAINT uknjsd10gr101fag1s1qflj29tj UNIQUE (name);

-- 논리 참조를 명시한 외래키 (앱은 FK 제약 없이 운영하지만, ERD 관계 표시용)
ALTER TABLE ONLY public.erd_domain
    ADD CONSTRAINT fk_erd_domain_room_id FOREIGN KEY (room_id) REFERENCES public.erd_room (id);
ALTER TABLE ONLY public.erd_table
    ADD CONSTRAINT fk_erd_table_room_id FOREIGN KEY (room_id) REFERENCES public.erd_room (id);
ALTER TABLE ONLY public.erd_column
    ADD CONSTRAINT fk_erd_column_table_id FOREIGN KEY (table_id) REFERENCES public.erd_table (id);
ALTER TABLE ONLY public.erd_relation
    ADD CONSTRAINT fk_erd_relation_room_id FOREIGN KEY (room_id) REFERENCES public.erd_room (id);
ALTER TABLE ONLY public.erd_relation
    ADD CONSTRAINT fk_erd_relation_child_table_id FOREIGN KEY (child_table_id) REFERENCES public.erd_table (id);
ALTER TABLE ONLY public.erd_relation
    ADD CONSTRAINT fk_erd_relation_parent_table_id FOREIGN KEY (parent_table_id) REFERENCES public.erd_table (id);
ALTER TABLE ONLY public.erd_memo
    ADD CONSTRAINT fk_erd_memo_room_id FOREIGN KEY (room_id) REFERENCES public.erd_room (id);
ALTER TABLE ONLY public.erd_history
    ADD CONSTRAINT fk_erd_history_room_id FOREIGN KEY (room_id) REFERENCES public.erd_room (id);
